### ISSUE TITLE
how can setting quartz concurrent attr?

### ISSUE THREAD

**Issue by maoxiangyi** [EalenXie/SpringBoot-Quartz#1]
Quartz轮训任务，需要配置一个参数，这个参数来控制Job任务是否并行，这个参数是concurrent。默认是true，参考spring源码如下：

如果concurrent设为true，到了指定的时间就如去执行，不管上一次有没有执行完，如有一个Job每隔2分钟执行一次，但是每次要执行5分钟，这就出现了几次并行的情况，可能之间有些操作有相互影响（看业务场景）；

如果concurrent设为false，类似于串行，这个Job第一次没有执行完，第二次会推迟等待直到第一次执行完后，再执行第二次。

**Comment by EalenXie** [comment]
```java

package org.quartz;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * An annotation that marks a {@link Job} class as one that must not have multiple
 * instances executed concurrently (where instance is based-upon a {@link JobDetail} 
 * definition - or in other words based upon a {@link JobKey}).
 *
 * @see PersistJobDataAfterExecution
 * 
 * @author jhouse
 */
@Documented
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
public @interface DisallowConcurrentExecution {

}
```

参考说明 : [https://blog.csdn.net/fly_captain/article/details/83029440](https://blog.csdn.net/fly_captain/article/details/83029440)

本项目中DynamicJob的配置说明 : 

```java

/**
 * Created by EalenXie on 2018/6/4 14:29
 * :@DisallowConcurrentExecution : 此标记用在实现Job的类上面,意思是不允许并发执行.
 * :注意org.quartz.threadPool.threadCount线程池中线程的数量至少要多个,否则@DisallowConcurrentExecution不生效
 * :假如Job的设置时间间隔为3秒,但Job执行时间是5秒,设置@DisallowConcurrentExecution以后程序会等任务执行完毕以后再去执行,否则会在3秒时再启用新的线程执行
 */
@DisallowConcurrentExecution
@Component
public class DynamicJob implements Job {
    //.....
}
```

**Comment by maoxiangyi** [comment]
我想把程序改成支持多种任务类型的，目前正在扩展成能够执行mysql的。
大概的思路是spring容器初始化的时候，从数据库读取不同的DataSource config info，然后动态创建jdbc DataSource 加入spring容器进行管理。  
接着启动quartz任务，扫描db中的所有job信息并注册到scheduler。 任务信息中会指定当前任务的source(要执行sql的目标数据库)，process（sql语句），sink（将执行的结果存放到哪里）


期望更多交流，我QQ 171+418+298

**Comment by maoxiangyi** [comment]
![20190426105457](https://user-images.githubusercontent.com/5219923/56780413-c5932b80-6811-11e9-8841-d4a03f9a426e.png)
这是目前整下修改的内容

**Comment by EalenXie** [comment]
道友如果是想在我的项目上做更改的话，可以发起pull requests；因为这个项目的核心实现和目的其实是定时执行 java -jar 。如果道友是为了单独做新任务实现的话，可能要另立一个新工程。




------------------ 原始邮件 ------------------
发件人: "毛祥溢"<notifications@github.com>; 
发送时间: 2019年4月26日(星期五) 上午10:55
收件人: "EalenXie/SpringBoot-Quartz"<SpringBoot-Quartz@noreply.github.com>; 
抄送: "EalenXie"<ealenxie@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [EalenXie/SpringBoot-Quartz] how can setting quartz concurrentattr? (#1)





 这是目前整下修改的内容
