### ISSUE TITLE
jar_path 的问题

### ISSUE THREAD

**Issue by chenziwucodeing** [EalenXie/SpringBoot-Quartz#2]
为什么的你执行是一个 jar_path。不是具体的一个类中的某个方法。

**Comment by EalenXie** [comment]
我是做为调度中心使用的，如果只是想要写个定时任务，自定义逻辑,启动,暂停,恢复,删除,修改的话，可以参考[https://github.com/EalenXie/springboot-quartz-simple](https://github.com/EalenXie/springboot-quartz-simple)

**Comment by chenziwucodeing** [comment]
> 我是做为调度中心使用的，如果只是想要写个定时任务，自定义逻辑,启动,暂停,恢复,删除,修改的话，可以参考https://github.com/EalenXie/springboot-quartz-simple
我是第一次在GIT 留言。很高能收到你的回复。
